name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # or the name of your default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.2
        with:
          folder: . # the folder in your repository that you want to deploy
          target_branch: gh-pages # the branch name for your GitHub Pages site
          token: ${{ secrets.GITHUB_TOKEN }} # the GitHub token to authenticate the deployment
